### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rafaelklaessen** [rafaelklaessen/keep-clone#37]
@Titogelo I was wondering, should I work out the app [tests](https://github.com/rafaelklaessen/keep-clone/tree/master/test)?

**Comment by Titogelo** [comment]
I am sorry but lately I've got a lot of work to do, that's why I haven't been that active.

Unit testing is always always recommended. I would say it is really important especially when your project grows. If you want to add new functionality but at the same time, you want to be sure that the basic stuff works... unit testing can save you a lot of time. 

If you get used to this good programming practices you will be a better software engineer.

Good luck!

**Comment by rafaelklaessen** [comment]
I've created an issue for it: #40
