### ISSUE TITLE
Error found

### ISSUE THREAD

**Issue by Titogelo** [rafaelklaessen/keep-clone#38]
It does not work for me know. I get the following error:
http://localhost:9000/assets/javascripts/main.js 404 (Not Found)

I tried in scala (sbt run) and with activator ui and both the same problem. I've never compiled the javascript with babel before and it always worked. Do I need to do something different now?

;-) let me know.  

Best.

**Comment by rafaelklaessen** [comment]
Yes, I've removed the compiled JS so you'll need to compile it yourself with Babel.
I did this because it doesn't really make sense to store autocompiled files on GitHub.

If you have NodeJS with Babel globally installed you can run `babel es6 --watch --out-file javascripts/main.js` in the public directory. That should work :)
